using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace DependencyInjectionRegistration.Generator;

[Generator]
public sealed class DiRegistrationGenerator : IIncrementalGenerator
{
    private const string ScopedAttr = "DependencyInjectionRegistration.RegisterScopedAttribute";
    private const string SingletonAttr = "DependencyInjectionRegistration.RegisterSingletonAttribute";
    private const string TransientAttr = "DependencyInjectionRegistration.RegisterTransientAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static c => c.AddSource("RegistrationAttributes.g.cs", SourceText.From("""
// <auto-generated />
namespace DependencyInjectionRegistration;
[global::System.AttributeUsage(global::System.AttributeTargets.Class)] public sealed class RegisterScopedAttribute : global::System.Attribute {}
[global::System.AttributeUsage(global::System.AttributeTargets.Class)] public sealed class RegisterSingletonAttribute : global::System.Attribute {}
[global::System.AttributeUsage(global::System.AttributeTargets.Class)] public sealed class RegisterTransientAttribute : global::System.Attribute {}
""", Encoding.UTF8)));

        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
            static (n, _) => n is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
            static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node) as INamedTypeSymbol)
            .Where(static s => s is not null)!;

        var collected = candidates.Collect();
        context.RegisterSourceOutput(collected, static (spc, symbols) =>
        {
            var regs = new List<(string Method, string Service, string Impl)>();
            foreach (var type in symbols.Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>())
            {
                var hasScoped = Has(type, ScopedAttr);
                var hasSingleton = Has(type, SingletonAttr);
                var hasTransient = Has(type, TransientAttr);
                var count = (hasScoped ? 1 : 0) + (hasSingleton ? 1 : 0) + (hasTransient ? 1 : 0);
                if (count == 0) continue;
                if (count > 1)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(Diags.ConflictingLifetime, type.Locations.FirstOrDefault(), type.Name));
                    continue;
                }
                var method = hasScoped ? "AddScoped" : hasSingleton ? "AddSingleton" : "AddTransient";
                var nonFrameworkInterfaces = type.Interfaces.Where(i => !i.ContainingNamespace.ToDisplayString().StartsWith("System", StringComparison.Ordinal)).ToArray();
                if (nonFrameworkInterfaces.Length == 1)
                {
                    regs.Add((method, "global::" + nonFrameworkInterfaces[0].ToDisplayString(), "global::" + type.ToDisplayString()));
                }
                else if (nonFrameworkInterfaces.Length == 0)
                {
                    var fq = "global::" + type.ToDisplayString();
                    regs.Add((method, fq, fq));
                }
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("namespace DependencyInjectionRegistration.Demo.Generated;");
            sb.AppendLine("public static partial class GeneratedServiceCollectionExtensions");
            sb.AppendLine("{");
            sb.AppendLine("    public static IServiceCollection AddGeneratedServices(this IServiceCollection services)");
            sb.AppendLine("    {");
            foreach (var r in regs.OrderBy(x => x.Impl, StringComparer.Ordinal))
            {
                if (r.Service == r.Impl)
                    sb.Append("        services.").Append(r.Method).Append('<').Append(r.Impl).AppendLine(">();");
                else
                    sb.Append("        services.").Append(r.Method).Append('<').Append(r.Service).Append(", ").Append(r.Impl).AppendLine(">();");
            }
            sb.AppendLine("        return services;");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            spc.AddSource("GeneratedServiceCollectionExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static bool Has(INamedTypeSymbol type, string attr) => type.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == attr);

    private static class Diags
    {
        public static readonly DiagnosticDescriptor ConflictingLifetime = new("DI001", "Conflicting lifetime attributes", "Service '{0}' has multiple lifetime attributes", "DependencyInjectionRegistration", DiagnosticSeverity.Error, true);
    }
}
