using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ReflectionFreeSerialization.Generator;

[Generator]
public sealed class ReflectionFreeSerializationGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "ReflectionFreeSerialization.GenerateJsonSerializableAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static initContext =>
        {
            initContext.AddSource(
                "GenerateJsonSerializableAttribute.g.cs",
                SourceText.From(
                    """
                    // <auto-generated />
                    namespace ReflectionFreeSerialization;

                    [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct)]
                    public sealed class GenerateJsonSerializableAttribute : global::System.Attribute
                    {
                    }
                    """,
                    Encoding.UTF8));
        });

        IncrementalValuesProvider<INamedTypeSymbol> candidates = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                static (node, _) => node is TypeDeclarationSyntax,
                static (syntaxContext, _) => (INamedTypeSymbol)syntaxContext.TargetSymbol);

        IncrementalValueProvider<INamedTypeSymbol[]> collected = candidates
            .Collect()
            .Select(static (symbols, _) =>
            {
                return symbols
                    .Distinct(SymbolEqualityComparer.Default)
                    .OfType<INamedTypeSymbol>()
                    .OrderBy(static symbol => symbol.ToDisplayString(), StringComparer.Ordinal)
                    .ToArray();
            });

        context.RegisterSourceOutput(collected, static (productionContext, symbols) =>
        {
            if (symbols.Length == 0)
            {
                return;
            }

            StringBuilder builder = new();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#nullable enable");
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Text.Json;");
            builder.AppendLine("using System.Text.Json.Serialization;");
            builder.AppendLine("using System.Text.Json.Serialization.Metadata;");
            builder.AppendLine();
            builder.AppendLine("namespace ReflectionFreeSerialization.Demo.Generated;");
            builder.AppendLine();

            foreach (INamedTypeSymbol symbol in symbols)
            {
                string qualifiedType = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                builder.Append("[JsonSerializable(typeof(");
                builder.Append(qualifiedType);
                builder.AppendLine("))]");
            }

            builder.AppendLine("public sealed partial class GeneratedJsonContext : JsonSerializerContext");
            builder.AppendLine("{");
            builder.AppendLine("    private static readonly JsonSerializerOptions DefaultOptions = new();");
            builder.AppendLine("    private static readonly IJsonTypeInfoResolver Resolver = new DefaultJsonTypeInfoResolver();");
            builder.AppendLine("    public static GeneratedJsonContext Default { get; } = new(DefaultOptions);");
            builder.AppendLine();
            builder.AppendLine("    public GeneratedJsonContext() : base(new JsonSerializerOptions())");
            builder.AppendLine("    {");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    public GeneratedJsonContext(JsonSerializerOptions options) : base(options)");
            builder.AppendLine("    {");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    protected override JsonSerializerOptions? GeneratedSerializerOptions => Options;");
            builder.AppendLine();
            builder.AppendLine("    public override JsonTypeInfo? GetTypeInfo(Type type)");
            builder.AppendLine("    {");
            builder.AppendLine("        return Resolver.GetTypeInfo(type, Options);");
            builder.AppendLine("    }");
            builder.AppendLine();

            foreach (INamedTypeSymbol symbol in symbols)
            {
                string qualifiedType = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                builder.Append("    public JsonTypeInfo<");
                builder.Append(qualifiedType);
                builder.Append("> ");
                builder.Append(symbol.Name);
                builder.AppendLine(" => (JsonTypeInfo<" + qualifiedType + ">)Resolver.GetTypeInfo(typeof(" + qualifiedType + "), Options)!;");
                builder.AppendLine();
            }

            builder.AppendLine("}");

            productionContext.AddSource("GeneratedJsonContext.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        });
    }
}
