using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace BoilerplateMapping.Generator;

[Generator]
public sealed class MapperGenerator : IIncrementalGenerator
{
    private const string Attr = "BoilerplateMapping.GenerateMapperAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static c => c.AddSource("GenerateMapperAttribute.g.cs", SourceText.From("""
// <auto-generated />
namespace BoilerplateMapping;

[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
public sealed class GenerateMapperAttribute : global::System.Attribute
{
    public GenerateMapperAttribute(global::System.Type sourceType, global::System.Type targetType)
    {
    }
}
""", Encoding.UTF8)));

        var mappings = context.SyntaxProvider.ForAttributeWithMetadataName(
            Attr,
            static (n, _) => n is ClassDeclarationSyntax,
            static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(mappings, static (spc, mapperClass) =>
        {
            var attrs = mapperClass.GetAttributes().Where(a => a.AttributeClass?.ToDisplayString() == Attr);
            foreach (var attr in attrs)
            {
                var src = attr.ConstructorArguments.Length > 0 ? attr.ConstructorArguments[0].Value as INamedTypeSymbol : null;
                var dst = attr.ConstructorArguments.Length > 1 ? attr.ConstructorArguments[1].Value as INamedTypeSymbol : null;
                if (src is null)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(Diags.MissingSource, mapperClass.Locations.FirstOrDefault()));
                    continue;
                }
                if (dst is null)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(Diags.MissingTarget, mapperClass.Locations.FirstOrDefault()));
                    continue;
                }

                var srcProps = src.GetMembers().OfType<IPropertySymbol>().Where(p => p.DeclaredAccessibility == Accessibility.Public && p.GetMethod is not null).ToArray();
                var dstProps = dst.GetMembers().OfType<IPropertySymbol>().Where(p => p.DeclaredAccessibility == Accessibility.Public && (p.SetMethod is not null || p.IsReadOnly == false)).ToArray();
                var matches = srcProps.Join(dstProps, s => s.Name, d => d.Name, (s, d) => new { s, d })
                    .Where(p => SymbolEqualityComparer.Default.Equals(p.s.Type, p.d.Type)).ToArray();

                if (matches.Length == 0)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(Diags.NoMatches, mapperClass.Locations.FirstOrDefault(), src.Name, dst.Name));
                    continue;
                }

                var ns = mapperClass.ContainingNamespace.IsGlobalNamespace ? "BoilerplateMapping.Demo" : mapperClass.ContainingNamespace.ToDisplayString();
                var code = new StringBuilder();
                code.AppendLine("// <auto-generated />");
                code.AppendLine("#nullable enable");
                code.Append("namespace ").Append(ns).AppendLine(";");
                code.AppendLine();
                code.Append("public static partial class ").Append(mapperClass.Name).AppendLine();
                code.AppendLine("{");
                code.Append("    public static global::").Append(dst.ToDisplayString()).Append(" To").Append(dst.Name).Append("(this global::").Append(src.ToDisplayString()).AppendLine(" source)");
                code.AppendLine("    {");
                code.Append("        return new global::").Append(dst.ToDisplayString()).AppendLine();
                code.AppendLine("        {");
                foreach (var m in matches)
                {
                    code.Append("            ").Append(m.d.Name).Append(" = source.").Append(m.s.Name).AppendLine(",");
                }
                code.AppendLine("        };");
                code.AppendLine("    }");
                code.AppendLine("}");
                spc.AddSource($"{mapperClass.Name}.{src.Name}_to_{dst.Name}.g.cs", SourceText.From(code.ToString(), Encoding.UTF8));
            }
        });
    }

    private static class Diags
    {
        public static readonly DiagnosticDescriptor MissingSource = new("MAP001", "Missing source type", "GenerateMapper requires a valid source type", "BoilerplateMapping", DiagnosticSeverity.Error, true);
        public static readonly DiagnosticDescriptor MissingTarget = new("MAP002", "Missing target type", "GenerateMapper requires a valid target type", "BoilerplateMapping", DiagnosticSeverity.Error, true);
        public static readonly DiagnosticDescriptor NoMatches = new("MAP003", "No matching properties", "No matching assignable properties were found between '{0}' and '{1}'", "BoilerplateMapping", DiagnosticSeverity.Error, true);
    }
}
