using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ValidationCode.Generator;

[Generator]
public sealed class ValidationGenerator : IIncrementalGenerator
{
    private const string Marker = "ValidationCode.GenerateValidatorAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static c => c.AddSource("GenerateValidatorAttribute.g.cs", SourceText.From("""
// <auto-generated />
namespace ValidationCode;

[global::System.AttributeUsage(global::System.AttributeTargets.Class)]
public sealed class GenerateValidatorAttribute : global::System.Attribute { }
""", Encoding.UTF8)));

        var models = context.SyntaxProvider.ForAttributeWithMetadataName(Marker, static (n, _) => n is ClassDeclarationSyntax, static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(models, static (spc, model) =>
        {
            var ns = model.ContainingNamespace.IsGlobalNamespace ? "ValidationCode.Demo.Generated" : model.ContainingNamespace + ".Generated";
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine("public sealed record ValidationError(string PropertyName, string Message);");
            sb.AppendLine("public sealed record ValidationResult(bool IsValid, System.Collections.Generic.IReadOnlyList<ValidationError> Errors);");
            sb.Append("public static partial class ").Append(model.Name).AppendLine("Validator");
            sb.AppendLine("{");
            sb.Append("    public static ValidationResult Validate(global::").Append(model.ToDisplayString()).AppendLine(" request)");
            sb.AppendLine("    {");
            sb.AppendLine("        var errors = new System.Collections.Generic.List<ValidationError>();");

            foreach (var prop in model.GetMembers().OfType<IPropertySymbol>().Where(p => p.DeclaredAccessibility == Accessibility.Public))
            {
                foreach (var attr in prop.GetAttributes())
                {
                    var name = attr.AttributeClass?.Name;
                    if (name == "RequiredAttribute")
                    {
                        if (prop.Type.SpecialType == SpecialType.System_String)
                        {
                            sb.Append("        if (string.IsNullOrWhiteSpace(request.").Append(prop.Name).AppendLine("))");
                            sb.Append("            errors.Add(new ValidationError(\"").Append(prop.Name).AppendLine("\", \"Value is required.\"));");
                        }
                    }
                    else if (name == "StringLengthAttribute")
                    {
                        int max = (int)attr.ConstructorArguments[0].Value!;
                        int min = 0;
                        foreach (var na in attr.NamedArguments) if (na.Key == "MinimumLength" && na.Value.Value is int iv) min = iv;
                        sb.Append("        if (request.").Append(prop.Name).Append(" is not null && (request.").Append(prop.Name).Append(".Length < ").Append(min).Append(" || request.").Append(prop.Name).Append(".Length > ").Append(max).AppendLine("))");
                        sb.Append("            errors.Add(new ValidationError(\"").Append(prop.Name).Append("\", \"Length must be between ").Append(min).Append(" and ").Append(max).AppendLine(".\"));");
                    }
                    else if (name == "RangeAttribute")
                    {
                        var min = attr.ConstructorArguments[0].Value?.ToString() ?? "0";
                        var max = attr.ConstructorArguments[1].Value?.ToString() ?? "0";
                        if (prop.Type.SpecialType == SpecialType.System_Decimal)
                        {
                            min += "m";
                            max += "m";
                        }

                        sb.Append("        if (request.").Append(prop.Name).Append(" < ").Append(min).Append(" || request.").Append(prop.Name).Append(" > ").Append(max).AppendLine(")");
                        sb.Append("            errors.Add(new ValidationError(\"").Append(prop.Name).Append("\", \"Value must be between ").Append(min).Append(" and ").Append(max).AppendLine(".\"));");
                    }
                    else if (name is not null && name != "GenerateValidatorAttribute")
                    {
                        spc.ReportDiagnostic(Diagnostic.Create(Diags.UnsupportedAttribute, prop.Locations.FirstOrDefault(), attr.AttributeClass!.ToDisplayString(), model.Name, prop.Name));
                    }
                }
            }

            sb.AppendLine("        return new ValidationResult(errors.Count == 0, errors);");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            spc.AddSource($"{model.Name}.Validator.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static class Diags
    {
        public static readonly DiagnosticDescriptor UnsupportedAttribute = new("VAL001", "Unsupported validation attribute", "Attribute '{0}' is not supported on model '{1}', property '{2}'", "ValidationCode", DiagnosticSeverity.Error, true);
    }
}
